[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.message_control]
enable = "all"
# bad-continuation and bad-whitespace are required by black
disable = """
    bad-continuation,
    bad-whitespace,
    invalid-name,
    locally-disabled,
    missing-class-docstring,
    missing-function-docstring,
    missing-module-docstring,
    no-else-return,
    pointless-string-statement,
    suppressed-message,
    too-few-public-methods,
    too-many-instance-attributes,
    too-many-lines,
    unidiomatic-typecheck,
    unnecessary-pass
"""
